steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/io-p-1:$COMMIT_SHA', '.'] # . oznacza bieżący katalog (czyli root repozytorium)
images:
- 'gcr.io/$PROJECT_ID/io-p-1:$COMMIT_SHA'
